export const DROP_SOURCE = {
    EVERYWHERE: 0,
    GUILD_HUNT: 1,
}

export const EQUIPMENT_SLOT_NAME_MAP = {
    0: "WEAPON",
    1: "HELMET",
    2: "ARMOR",
    3: "NECKLACE",
    4: "RING",
    5: "OTHER",
}

export const EQUIPMENT_SLOT = {
    WEAPON: 0,
    HELMET: 1,
    ARMOR: 2,
    RING: 3,
    NECKLACE: 4,
    OTHER: 5,
}

export const ATTRIBUTE_NAME_MAP = {
    0: "NONE",
    1: "STRENGTH",
    2: "DEXTERITY",
    3: "INTELLIGENCE",
}

export const ATTRIBUTE = {
    NONE: 0,
    STRENGTH: 1,
    DEXTERITY: 2,
    INTELLIGENCE: 3,
}

export const PRIMARY_STAT_NAME_MAP = {
    0: "ATTACK",
    1: "DEFENCE",
    2: "AGILITY",
}

export const PRIMARY_STAT = {
    ATTACK: 0,
    DEFENCE: 1,
    AGILITY: 2,
}

export const ROLE_NAME_MAP = {
    0: "OFFENSIVE",
    1: "DEFENSIVE",
    2: "CONTROL",
    3: "SUPPORT",
}

export const ROLE = {
    OFFENSIVE: 0,
    DEFENSIVE: 1,
    CONTROL: 2,
    SUPPORT: 3,
}

export const PERKS = {
    NOTHING: { id: -1, name: "Nothing" },
    HEALTH_PERCENT: { id: 0, name: "Health Percent" },
    ATTACK_PERCENT: { id: 1, name: "Attack Percent" },
    DEFENCE_PERCENT: { id: 2, name: "Defence Percent" },
    AGILITY_PERCENT: { id: 3, name: "Agility Percent" },
    HEALTH_FLAT: { id: 4, name: "Health Flat" },
    ATTACK_FLAT: { id: 5, name: "Attack Flat" },
    DEFENCE_FLAT: { id: 6, name: "Defence Flat" },
    AGILITY_FLAT: { id: 7, name: "Agility Flat" },
    CRIT_CHANCE: { id: 8, name: "Crit Chance" },
    CRIT_RESISTANCE: { id: 9, name: "Crit Resistance" },
    CRIT_DAMAGE: { id: 10, name: "Crit Damage" },
    CRIT_DAMAGE_REDUCTION: { id: 11, name: "Crit Damage Reduction" },
    ACCURACY: { id: 12, name: "Accuracy" },
    RESISTANCE: { id: 13, name: "Resistance" },
    BOSS_DAMAGE: { id: 14, name: "Boss Damage" },
    BOSS_DAMAGE_REDUCTION: { id: 15, name: "Boss Damage Reduction" },
    AOE_DAMAGE_REDUCTION: { id: 16, name: "AoE Damage Reduction" },
    AP_DAMAGE_REDUCTION: { id: 17, name: "AP Damage Reduction" },
    LIFE_STEAL: { id: 18, name: "Life Steal" },
    HEALING_EFFICIENCY: { id: 19, name: "Healing Efficiency" },
    HEALING_RECEIVED: { id: 20, name: "Healing Received" },
    FIRE_DAMAGE: { id: 21, name: "Fire Damage" },
    NATURE_DAMAGE: { id: 22, name: "Nature Damage" },
    WATER_DAMAGE: { id: 23, name: "Water Damage" },
    LIGHT_DAMAGE: { id: 24, name: "Light Damage" },
    SHADOW_DAMAGE: { id: 25, name: "Shadow Damage" },
    FIRE_DAMAGE_REDUCTION: { id: 26, name: "Fire Damage Reduction" },
    NATURE_DAMAGE_REDUCTION: { id: 27, name: "Nature Damage Reduction" },
    WATER_DAMAGE_REDUCTION: { id: 28, name: "Water Damage Reduction" },
    LIGHT_DAMAGE_REDUCTION: { id: 29, name: "Light Damage Reduction" },
    SHADOW_DAMAGE_REDUCTION: { id: 30, name: "Shadow Damage Reduction" },
    MAIN_STAT_PERCENT: { id: 31, name: "Main Attribute Percent" },
    MAIN_STAT_FLAT: { id: 32, name: "Main Attribute Flat" },
}

export const POSSIBLE_PERKS = {
    WEAPONS: [
        "MAIN_STAT_FLAT", "MAIN_STAT_PERCENT", "HEALTH_PERCENT", "ACCURACY", "CRIT_DAMAGE",
        "CRIT_CHANCE", "BOSS_DAMAGE", "LIFE_STEAL", "HEALING_EFFICIENCY", "HEALING_RECEIVED"
    ],
    HELMETS: [
        "MAIN_STAT_FLAT", "MAIN_STAT_PERCENT", "HEALTH_FLAT", "HEALTH_PERCENT", "ACCURACY",
        "CRIT_DAMAGE", "BOSS_DAMAGE_REDUCTION", "CRIT_RESISTANCE", "SHADOW_DAMAGE_REDUCTION", "LIGHT_DAMAGE_REDUCTION"
    ],
    ARMORS: [
        "MAIN_STAT_PERCENT", "HEALTH_FLAT", "HEALTH_PERCENT", "RESISTANCE", "HEALING_RECEIVED",
        "CRIT_DAMAGE_REDUCTION", "AOE_DAMAGE_REDUCTION", "FIRE_DAMAGE_REDUCTION", "NATURE_DAMAGE_REDUCTION", "WATER_DAMAGE_REDUCTION"
    ],
    RINGS: [
        "MAIN_STAT_PERCENT", "AP_DAMAGE_REDUCTION", "CRIT_DAMAGE_REDUCTION", "CRIT_RESISTANCE", "LIFE_STEAL",
        "HEALING_EFFICIENCY", "HEALING_RECEIVED", "FIRE_DAMAGE", "NATURE_DAMAGE", "WATER_DAMAGE"
    ],
    NECKLACES: [
        "ACCURACY", "RESISTANCE", "CRIT_DAMAGE", "CRIT_CHANCE", "BOSS_DAMAGE",
        "AP_DAMAGE_REDUCTION", "HEALING_EFFICIENCY", "SHADOW_DAMAGE", "LIGHT_DAMAGE", "CRIT_RESISTANCE",
        "BOSS_DAMAGE_REDUCTION",
    ],
}

export const RARITY_NAME_MAP = {
    0: "COMMON",
    1: "UNCOMMON",
    2: "RARE",
    3: "EPIC",
    4: "LEGENDARY",
    5: "MYTHICAL",
}

export const RARITY = {
    COMMON: 0,
    UNCOMMON: 1,
    RARE: 2,
    EPIC: 3,
    LEGENDARY: 4,
    MYTHICAL: 5,
}

export const ELEMENT_NAME_MAP = {
    0: "FIRE",
    1: "WATER",
    2: "NATURE",
    3: "LIGHT",
    4: "SHADOW",
    5: "VOID"
}

export const ELEMENT = {
    FIRE: 0,
    WATER: 1,
    NATURE: 2,
    LIGHT: 3,
    SHADOW: 4,
    VOID: 5,
}

export const UNIQUE_SKILLS = {
    NOTHING: 0,

    // STRENGTH
    PUMPKIN_SCYTHE: { id: 100, description: "$e chance to get an extra turn when killing an enemy.", rarityEffect: [1.20, 1.25, 1.30, 1.35] },
    DRILL_SLAMMER: { id: 101, description: "Ultimate Skill has a $e chance to deal 6% extra true damage.", rarityEffect: [1.32, 1.40, 1.48, 1.56] },
    LIGHT_AXE: { id: 102, description: "Increases splash damage (ignores primary target) by $e", rarityEffect: [1.05, 1.06, 1.08, 1.10] },
    FROST_BINDER: { id: 103, description: "+$e damage on targets with Freeze.", rarityEffect: [1.05, 1.06, 1.08, 1.10] },
    HYDRAS_BITE: { id: 104, description: "Critical hits have a $e chance to inflinct Poison on the target for 2 turns.", rarityEffect: [1.20, 1.25, 1.30, 1.35] },
    VAMPIRES_STAKE: { id: 105, description: "Critical hits have a $e chance to inflinct Cursed on the target for 2 turns", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    SKY_PIERCER: { id: 106, description: "Primary Skill has a $e chance to ignore shields.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    VOID_PIERCER_LANCE: { id: 107, description: "Primary Skill has a $e chance to inflict DEF Down on target for 2 turns.", rarityEffect: [1.24, 1.30, 1.36, 1.42] },
    VOID_SPLITTER: { id: 108, description: "Ultimate Skill has a $e chance to deal 5% of missing max HP as extra true damage.", rarityEffect: [1.32, 1.40, 1.48, 1.56] },
    LIGHT_SWORD: { id: 109, description: "Increases Critical Chance by $e in turn 1 and every 3 turns.", rarityEffect: [1.16, 1.20, 1.24, 1.28] },
    SUN_SPLITTER: { id: 110, description: "Primary Skill has a $e chance to inflinct Blind on the target for 2 turns.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    RUST_BINDER: { id: 111, description: "Critical Hits have a $e chance to inflinct Bleeding on the target for 2 turns.", rarityEffect: [1.36, 1.45, 1.54, 1.63] },
    MAGMA_EDGE: { id: 112, description: "+$e damage on targets with Burn.", rarityEffect: [1.05, 1.06, 1.08, 1.10] },
    ROTTEN_MAUL: { id: 113, description: "Ultimate Skill has a $e chance to grant self 20% extra AP.", rarityEffect: [1.32, 1.40, 1.48, 1.56] },
    HOOK_HAMMER: { id: 114, description: "Increases Defense by $e in turn 1 and every 2 turns.", rarityEffect: [1.05, 1.06, 1.08, 1.10] },
    TITANS_MAUL: { id: 115, description: "Primary Skill deals $e Defense as true damage to 2 adjancent targets.", rarityEffect: [1.08, 1.10, 1.12, 1.14] },
    EARTH_BREAKER: { id: 116, description: "Primary Skill has a $e chance to inflinct AGI Down on target for 2 turns.", rarityEffect: [1.24, 1.30, 1.36, 1.42] },
    PROBLEM_SOLVER: { id: 117, description: "+$e Critical Damage on targets with Bleeding.", rarityEffect: [1.12, 1.15, 1.18, 1.21] },
    HARMONY: { id: 118, description: "All inflicted debuffs that cause damage over time have a $e chance to last 1 extra turn.", rarityEffect: [1.40, 1.50, 1.60, 1.70] },
    CHOPOCALYPSE: { id: 119, description: "Primary Skill has a $e chance to inflinct ATK Down on target for 1 turn.", rarityEffect: [1.24, 1.30, 1.36, 1.42] },
    SINGULARITY: { id: 120, description: "Ultimate Skill has a $e chance to inflict Echo on target for 2 turns.", rarityEffect: [1.40, 1.50, 1.60, 1.70] },
    GRAVEL_BUSTER: { id: 121, description: "If own HP are above 75%, Shield Strength increased by $e.", rarityEffect: [1.15, 1.20, 1.25, 1.30] },
    BIASED_WHEEL: { id: 122, description: "Primary Skill has a $e chance to inflict Burn on target for 1 turn.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },

    // INTELLIGENCE
    EMBRYONIC_CATALYST: { id: 200, description: "Cast Buffs (except Invincibility & Preservation) have a $e chance to last 1 extra turn.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    PEST_BRINGER: { id: 201, description: "Primary Skill has a $e chance to inflinct Poison on target for 2 turns.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    MIASMA_STAFF: { id: 201, description: "Deals $e extra true damage in turn 1 and every 3 turns.", rarityEffect: [1.08, 1.10, 1.12, 1.14] },
    FIRE_STARTER: { id: 202, description: "Primary Skill deals $e Attack as true damage to 1 adjancent target.", rarityEffect: [1.11, 1.15, 1.19, 1.23] },
    ICILE: { id: 203, description: "+$e Critical Chance on targets with Freeze", rarityEffect: [1.16, 1.20, 1.24, 1.28] },
    LIFE_CATALYST: { id: 204, description: "Critical hits heal all allies by $e of damage dealt.", rarityEffect: [1.05, 1.06, 1.08, 1.10] },
    ARCANE_CODEX: { id: 205, description: "Ultimate Skill has a $e chance to grant self AGI Up for 2 turns.", rarityEffect: [1.36, 1.45, 1.54, 1.63] },
    LAST_OATH: { id: 206, description: "Primary Skill deals $e Agility as true damage to 2 adjacent targets.", rarityEffect: [1.08, 1.10, 1.12, 1.14] },
    BASILISKS_EYE: { id: 207, description: "Primary Skill has a $e chance to inflict Petrified on target for 2 turns.", rarityEffect: [1.20, 1.25, 1.30, 1.35] },
    RAINBOW_STAFF: { id: 208, description: "Critical hits heal ally with lowest health (or self) by $e of damage dealth on the target.", rarityEffect: [1.12, 1.15, 1.18, 1.21] },
    SEED_OF_ROT: { id: 209, description: "Critical hits have a $e chance to inflict Sick on the target for 2 turns.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    TOME_OF_ETERNAL_FROST: { id: 210, description: "Primary Skill has a $e chance to inflinct Freeze on target for 1 turn.", rarityEffect: [1.16, 1.20, 1.24, 1.28] },
    GODS_VOW: { id: 211, description: "$e chance to get an extra turn when killing an enemy.", rarityEffect: [1.20, 1.25, 1.30, 1.35] },
    SOUL_CATALYST: { id: 212, description: "Cast Debuffs (except Stunned) have a $e chance to last 1 extra turn.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    ARCANE_PULSE: { id: 213, description: "Killing enemies has a $e chance to heal self by 15% of own HP", rarityEffect: [1.11, 1.15, 1.19, 1.23] },
    RESEARCH_LOG: { id: 214, description: "Primary Skill has a $e chance to inflinct Mute on target for 1 turn.", rarityEffect: [1.15, 1.20, 1.25, 1.30] },
    EQUILIBRIUM: { id: 215, description: "+$e Critical Chance on targets with Marked.", rarityEffect: [1.25, 1.30, 1.36, 1.42] },
    INSANITY_CATALYST: { id: 216, description: "Increases Critical Damage by $e in turn 1 and every 2 turns.", rarityEffect: [1.15, 1.20, 1.25, 1.30] },
    DUALITY: { id: 217, description: "Ultimate Skill heals the ally with the lowest HP by $e of total damage dealt.", rarityEffect: [1.08, 1.10, 1.12, 1.14] },
    DOOM_ROD: { id: 218, description: "Ultimate Skill has a $e chance to inflict Bound on target for 1 turn.", rarityEffect: [1.12, 1.15, 1.18, 1.21] },
    SINGULARITY_TOME: { id: 219, description: "Increases Splash Damage by $e.", rarityEffect: [1.05, 1.06, 1.08, 1.10] },

    // AGILITY
    BLASTER: { id: 300, description: "Critical hits heal self by $e of damage dealt.", rarityEffect: [1.07, 1.10, 1.13, 1.16] },
    BONE_BOW: { id: 301, description: "Heals self by $e of max HP when killing an enemy.", rarityEffect: [1.08, 1.10, 1.12, 1.14] },
    BOOMSTICK: { id: 302, description: "Increases splash damage (ignores primary target) by $e", rarityEffect: [1.05, 1.06, 1.08, 1.10] },
    WOLF_CLAWS: { id: 303, description: "$e chance to counter with Primary Skill once against attacker", rarityEffect: [1.24, 1.30, 1.36, 1.42] },
    CORKSCREW_KNUCKLE: { id: 304, description: "Primary Skill has a $e chance to inflinct Bleeding on target for 2 turns.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    SOUL_STABBER: { id: 305, description: "Primary Skill has a 60% chance to steal $e of target's current AP.", rarityEffect: [1.12, 1.15, 1.18, 1.21] },
    WHISPER_BLADE: { id: 306, description: "+$e Critical Damage on targets with DEF Down", rarityEffect: [1.12, 1.15, 1.18, 1.21] },
    STARFIRE_BALLISTA: { id: 307, description: "Primary Skill deals $e Agility as true damage to 2 adjacent targets.", rarityEffect: [1.08, 1.10, 1.12, 1.14] },
    BLACK_FEATHER_BOW: { id: 308, description: "Primary Skill has a $e chance to inflict Marked on target for 2 turns.", rarityEffect: [1.24, 1.30, 1.36, 1.42] },
    SHADOW_FANGS: { id: 309, description: "+$e damage on targets with Blind.", rarityEffect: [1.05, 1.06, 1.08, 1.10] },
    VORTEX_DANCER: { id: 310, description: "Critical hits have a $e chance to inflict AGI Down on the target for 1 turn.", rarityEffect: [1.40, 1.50, 1.60, 1.70] },
    RELICFANG_DAGGER: { id: 311, description: "Critical hits have a $e chance to reduce AP of the target by 20%.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    NEEDLE_POINT: { id: 312, description: "Critical hits have a $e chance to inflinct Marked on the target for 1 turn.", rarityEffect: [1.32, 1.40, 1.48, 1.56] },
    BRUTE_FORCE: { id: 313, description: "Primary Skill has a $e chance to inflict DEF Down on target for 2 turns.", rarityEffect: [1.24, 1.30, 1.36, 1.42] },
    CLAWTASTROPHE: { id: 314, description: "Ultimate Skill has a $e chance to grant self Crit Chance Up for 2 turns", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    STARFALL: { id: 315, description: "At the start of every 3rd turn, heals all allies for $e of own max HP.", rarityEffect: [1.04, 1.06, 1.08, 1.10] },
    TWILIGHT: { id: 316, description: "Critical hits have a $e chance to dispel 1 Buff from the target.", rarityEffect: [1.40, 1.50, 1.60, 1.70] },
    DICE_OF_DOOM: { id: 317, description: "Buffs (except Invincibility & Preservation) have a $e chance to extend their Duration by 1 round.", rarityEffect: [1.30, 1.36, 1.43, 1.50] },
    TUSK_FANG: { id: 318, description: "Ultimate Skill has a $e chance to grant the Caster ATK Up for 2 turns.", rarityEffect: [1.40, 1.50, 1.60, 1.70] },
}

export const STATUS_EFFECT_NAME_MAP = {
    0: "attack_up",
    1: "defense_up",
    2: "critical_chance_up",
    3: "critical_damage_up",
    4: "accuracy_up",
    5: "resistance_up",
    6: "agility_up",
    7: "critical_resistance",
    8: "invincibility",
    9: "recovery",
    10: "preservation",
    11: "shroud",
    12: "guard",
    13: "shield",
    14: "absorbing",
    15: "blessed",
    16: "attack_down",
    17: "defense_down",
    18: "critical_chance_down",
    19: "accuracy_down",
    20: "resistance_down",
    21: "agility_down",
    22: "blind",
    23: "marked",
    24: "sick",
    25: "cursed",
    26: "stunned",
    27: "sleep",
    28: "freeze",
    29: "petrified",
    30: "burn",
    31: "poison",
    32: "bleeding",
    33: "mute",
    34: "bound",
    35: "taunt",
    36: "confused",
    37: "cursed_flame",
    38: "hellfire",
    39: "hellfire_mode",
    40: "frozen_heart",
    41: "heating_up",
    42: "mjoellnir",
    43: "anubis_seal",
    44: "soulmate",
    45: "styx",
    46: "burrow",
    47: "defense_drone",
    48: "divine_shield",
    49: "ferryman",
    50: "feral",
    51: "wildfire",
    52: "fury",
    53: "hivemind",
    54: "hot_saw",
    55: "loa",
    56: "the_moon",
    57: "the_star",
    58: "the_sun",
    59: "wind_up",
    60: "war_forge",
    61: "drumbeat",
    62: "foresight",
    63: "ap_resistance",
    64: "arachnid",
    65: "bloodrage",
    66: "bunny",
    67: "pain_fueled",
    68: "blood_transfusion",
    69: "soul_harvest",
    70: "buzz_meter",
    71: "biomass",
    72: "ignited_ego",
    73: "life_after_death",
    74: "sludge",
    75: "detonator",
    76: "courage",
    77: "smoke",
    78: "mana_shield",
    79: "echo",
    80: "ionize",
    81: "fracture",
    82: "irradiate",
    83: "rift_step",
    84: "blacklist",
    85: "rooted",
    86: "ash",
    87: "phoenix_feather",
    88: "luck",
    89: "soul_core",
    90: "tempered"
};

export const STATUS_EFFECTS = {
    attack_up: { id: 0, modifier: 1.25 },
    defense_up: { id: 1, modifier: 1.45 },
    critical_chance_up: { id: 2, modifier: 1.20 },
    critical_damage_up: { id: 3, modifier: 1.50 },
    accuracy_up: { id: 4, modifier: 1.30 },
    resistance_up: { id: 5, modifier: 1.35 },
    agility_up: { id: 6, modifier: 1.30 },
    critical_resistance: { id: 7, modifier: 1.25 },
    invincibility: { id: 8 },
    recovery: { id: 9, modifier: 1.15 },
    preservation: { id: 10 },
    shroud: { id: 11 },
    guard: { id: 12, modifier: 1.25 },
    shield: { id: 13 },
    absorbing: { id: 14, modifier: 1.15 },
    blessed: { id: 15, modifier: 1.20 },
    attack_down: { id: 16, modifier: 1.25 },
    defense_down: { id: 17, modifier: 1.45 },
    critical_chance_down: { id: 18, modifier: 1.20 },
    accuracy_down: { id: 19, modifier: 1.40 },
    resistance_down: { id: 20, modifier: 1.15 },
    agility_down: { id: 21, modifier: 1.30 },
    blind: { id: 22, modifier: 1.30 },
    marked: { id: 23, modifier: 1.25 },
    sick: { id: 24 },
    cursed: { id: 25 },
    stunned: { id: 26 },
    sleep: { id: 27, modifier: 1.50 },
    freeze: { id: 28 },
    petrified: { id: 29 },
    burn: { id: 30, modifier: 1.03 },
    poison: { id: 31, modifier: 1.10 },
    bleeding: { id: 32, modifier: 1.25 },
    mute: { id: 33 },
    bound: { id: 34 },
    taunt: { id: 35 },
    confused: { id: 36 },
    cursed_flame: { id: 37, modifier: 1.50 },
    hellfire: { id: 38 },
    hellfire_mode: { id: 39 },
    frozen_heart: { id: 40 },
    heating_up: { id: 41 },
    mjoellnir: { id: 42 },
    anubis_seal: { id: 43 },
    soulmate: { id: 44 },
    styx: { id: 45 },
    burrow: { id: 46 },
    defense_drone: { id: 47 },
    divine_shield: { id: 48 },
    ferryman: { id: 49 },
    feral: { id: 50 },
    wildfire: { id: 51 },
    fury: { id: 52 },
    hivemind: { id: 53 },
    hot_saw: { id: 54 },
    loa: { id: 55 },
    the_moon: { id: 56 },
    the_star: { id: 57 },
    the_sun: { id: 58 },
    wind_up: { id: 59 },
    war_forge: { id: 60 },
    drumbeat: { id: 61 },
    foresight: { id: 62 },
    ap_resistance: { id: 63 },
    arachnid: { id: 64 },
    bloodrage: { id: 65 },
    bunny: { id: 66 },
    pain_fueled: { id: 67 },
    blood_transfusion: { id: 68 },
    soul_harvest: { id: 69 },
    buzz_meter: { id: 70 },
    biomass: { id: 71 },
    ignited_ego: { id: 72 },
    life_after_death: { id: 73 },
    sludge: { id: 74 },
    detonater: { id: 75 },
    courage: { id: 76 },
    smoke: { id: 77 },
    mana_shield: { id: 78 },
    echo: { id: 79 },
    ionize: { id: 80 },
    fracture: { id: 81 },
    irradiate: { id: 82 },
    rift_step: { id: 83 },
    blacklist: { id: 84 },
    rooted: { id: 85 },
    ash: { id: 86 },
    phoenix_feather: { id: 87 },
    luck: { id: 88 },
    soul_core: { id: 89 },
    tempered: { id: 90 }
}